### ISSUE TITLE
Using dejavu for TV advert detectio

### ISSUE THREAD

**Issue by hexagone083** [worldveil/dejavu#108]
Hello,
I tried to use dejavu in order to detect TV advert. I have an issue : false positive. I wrote a script that analayse continually the TV audio flow. My database contain all Jingle advertising (about 5 seconds per jingles). I have a lot of false positive, dejavu detect jingles and ther are n jingles. Do you know solution or configuration in order to detect correcly TV jingles ?
THank's in advance, Florian.

**Comment by eoffermann** [comment]
This sounds like there's a good chance you're recognizing minimally-unique portions of the original source.

It's hard to say without listening to the jingles in your database, but you might try re-fingerprinting the middle three seconds instead of the entire clip, if you haven't already. With music, we often discard the beginning and end of a song - a few seconds from either end - because that data is frequently unhelpful.

**Comment by hexagone083** [comment]
Thank you for your answer. I Will try your solution. Is there a parameter that will allow us fully analyse the jingle/song stored in the database ?
