### ISSUE TITLE
How to display several songs in comparison.

### ISSUE THREAD

**Issue by sszaharovd** [worldveil/dejavu#164]
Good afternoon. I looked at the description of your library and it interested me. The goal of my task is to compare 100-150 reference 111 vails with one and output all the files with which the original file is similar. How to implement this and did not understand it because it displays only one file. And that if the percentage of similarity is 100%. How can I correctly check for an approximate similarity of the file with the standards?

**Comment by CwbhX** [comment]
Hey mate, 
I'm pretty sure Will has left this repository for dead by now, but I don't think your idea would work without some modifications. Since how this works is he is generated SHA1 hashs based of the peak data, then when you match a song you are doing the same thing and then looking for those hashes, the only reasons you don't get the same number as the original song is because of noise. I don't think you could get too many peaks from other songs which would give you hash collisions, if anything that would be bad.

**Comment by mauriciorepetto** [comment]
@sszaharovd hi, if more than one results is what you need I've added that feature on my pr https://github.com/worldveil/dejavu/pull/205. Which also includes dejavu migration to 3.6.6, support for postgresql and a couple of features more. Feel free to try it and let me know your thoughts.
