### ISSUE TITLE
How do I choose a diffrent audio source?

### ISSUE THREAD

**Issue by henryfoster** [worldveil/dejavu#213]
How I can change the audiosource from microphone to my speaker? 
When I play a song on my PC for example via youtube I need to hold my microphone to my speaker.
How to get the sound directly from the speaker instead?

**Comment by NathanielCustom** [comment]
You cannot, without third-party software, have your system's audio chip sample the audio being sent to the audio out jack.

What I have done with success is running a cable from the audio out directly to my default audio in port.

A "microphone in" port can be prone to clip, so monitor the input level and adjust your line out levels.

If you want to still have your speakers working, you can install a y-splitter so that both the speakers and audio-in port are connected to your audio out, but you can expect attenuation and degraded audio quality.
