### ISSUE TITLE
Does this package supports Python 3 

### ISSUE THREAD

**Issue by valentindush** [worldveil/dejavu#300]
I had troubles using it.. because it uses python 2

**Comment by busterbeam** [comment]
❓maybe you can provide a specific error?

**Comment by tgrushka** [comment]
It seems the current PyPI version does not.
A `print "...` with no parentheses is certainly not Python 3 syntax.

```
pip install PyDejavu

Successfully installed PyDejavu-0.1.3

python -c 'from dejavu import Dejavu'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./.venv/lib/python3.11/site-packages/dejavu/__init__.py", line 61
    print "%s already fingerprinted, continuing..." % filename
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

**Comment by tgrushka** [comment]
Install from GitHub according to INSTALLATION.md:
```
pip install https://github.com/worldveil/dejavu/zipball/master
```
is broken as well as it's requiring an outdated version of numpy.

**Comment by busterbeam** [comment]
🤦‍♂️️ @tgrushka [PyDejavu-Rollong](https://pypi.org/project/PyDejavu-Rollong/) is the correct PyPI repository the one you used was someone else's fork of this repository that is 9 years out of date.

but sadly you are right about `numpy` as the way of so many applications now days, they get containerized because developers use libraries that are either really old (due to improper development processes) or still in alpha (thinking there is some benefit)
